version: '3'
services:
  scrapyd:
    container_name: timer
    image: countdowntimer:v0.8
    restart: unless-stopped
    networks:
      - scrapy_net  
networks:
  scrapy_net:
    name: scrapy
    driver: bridge
